name: Pylint Check

on:
  push:
    paths:
      - "**.py"
      - "**.yml"

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: TheTeamVivek/YukkiMusic
          ref: dev
          path: YukkiMusic

      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          path: current_repo
        
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pylint

      - name: Run Pylint Check
        run: |
          ls
          python current_repo/script.py

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Format Codes"
          commit_options: "--no-verify"
          repository: .
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Delete old workflow run
        uses: Viyomx/delete-workflow-runs@v1.0.1
