name: Pylint Check

on:
  push:
    paths:
      - "**.py"
      - "**.yml"

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout YukkiMusic
        uses: actions/checkout@v4
        with:
          repository: TheTeamVivek/YukkiMusic
          ref: dev
          path: YukkiMusic

      - name: Checkout YukkiMusic
        uses: actions/checkout@v4
        with:
          repository: Vivekkumar-in/TheApi
          ref: master
          path: TheApi
          
      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          path: current_dir
        
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          ls -R > current_dir/a.txt
          pip install pylint

   #   - name: Run Pylint Check
  #      run: |
   #        pylint --exit-zero --output-format=json --indent-string="    " --reports=no YukkiMusic/YukkiMusic TheApi/ > current_dir/warnings.json
    #       cd current_dir
    #       python script.py

      - name: Run Pylint Check
        run: |
          cd YukkiMusic
          pylint --exit-zero --output-format=json --indent-string="    " --reports=no . > ../current_dir/warnings.json
          cd ../current_dir
          python script.py
          
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "."
          commit_options: "--no-verify"
          repository: current_dir
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Delete old workflow run
        uses: Viyomx/delete-workflow-runs@v1.0.1
