name: Pylint Check


on:
  push:
    paths:
      - "**.py"
      - "**.yml"
  workflow_dispatch:
jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout YukkiMusic
        uses: actions/checkout@v4
        with:
          repository: TheTeamVivek/YukkiMusic
          ref: master
          path: YukkiMusic
          
      - name: Checkout Current Repository
        uses: actions/checkout@v4
        with:
          path: current_dir
        
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install git+https://github.com/pylint-dev/pylint@main

      - name: Run Pylint Check
        run: |
          cp current_dir/.pylintrc YukkiMusic/.pylintrc
          cd current_dir
          find . -mindepth 1 ! -name 'script.py' ! -name '.pylintrc' ! -path './.git' ! -path './.git/*' ! -path './.github' ! -path './.github/*' -exec rm -rf {} +
         
          cd ../YukkiMusic
          pylint --exit-zero --output-format=json --indent-string="    " --reports=no . > ../current_dir/warnings.json
          cd ../current_dir
          python script.py
          
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update pylint warnings"
          commit_options: "--no-verify"
          repository: current_dir
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
